# Generated by Django 4.2.6 on 2023-11-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_company_workinghours_serviceatnonbusinesshours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_radio', models.BooleanField(default=False)),
                ('has_audio_cd', models.BooleanField(default=False)),
                ('has_mp3', models.BooleanField(default=False)),
                ('has_usb', models.BooleanField(default=False)),
                ('has_aux', models.BooleanField(default=False)),
                ('has_bluetooth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tank_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fuel_consumption', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fuel_type', models.CharField(max_length=50)),
                ('drive_type', models.CharField(max_length=50)),
                ('abs_system', models.BooleanField(default=False)),
                ('ebd_system', models.BooleanField(default=False)),
                ('esp_system', models.BooleanField(default=False)),
                ('transmission', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_license_category', models.CharField(max_length=50)),
                ('seats', models.PositiveIntegerField()),
                ('number_of_doors', models.PositiveIntegerField()),
                ('air_conditioning', models.BooleanField(default=False)),
                ('interior', models.CharField(max_length=50)),
                ('roof', models.CharField(max_length=50)),
                ('powered_windows', models.BooleanField(default=False)),
                ('airbags', models.BooleanField(default=False)),
                ('side_wheel', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('rear_view_camera', models.BooleanField(default=False)),
                ('parking_assist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='car_gallery/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='carMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('year_of_manufacture', models.PositiveIntegerField()),
                ('body_color', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=255)),
                ('insurance_company', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=30, unique=True)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('franchise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlimited_mileage', models.BooleanField(default=False)),
                ('limited_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('overage_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistrationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('registration_date', models.DateField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_address', models.TextField()),
                ('engine_number', models.CharField(max_length=30, unique=True)),
                ('chassis_number', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending Moderation', 'Pending Moderation'), ('Available for Sale', 'Available for Sale'), ('Internal Use Only', 'Internal Use Only')], default='Pending Moderation', max_length=50)),
                ('moderation_date', models.DateField(blank=True, null=True)),
                ('car_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cargallery')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.insurance')),
                ('mileage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mileage')),
                ('price_and_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.priceandconditions')),
            ],
        ),
    ]
