# Generated by Django 4.2.6 on 2023-11-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_caraudiofeatures_cardetails_carextras_carfeatures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_color',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
