# Generated by Django 4.2.6 on 2023-11-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_car_car_gallery_remove_cargallery_car_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carMake',
        ),
        migrations.RemoveField(
            model_name='car',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_and_conditions',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='vehicleregistrationcertificate',
            name='vehicle_model',
        ),
        migrations.AddField(
            model_name='caraudiofeatures',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
        migrations.AddField(
            model_name='mileage',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
        migrations.AddField(
            model_name='priceandconditions',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
        migrations.AddField(
            model_name='vehicleregistrationcertificate',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
    ]
