# Generated by Django 4.2.6 on 2023-11-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_carmake_remove_car_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='coverage_amount',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='policy_number',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='start_date',
        ),
    ]
