# Generated by Django 4.2.6 on 2023-11-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_insurance_coverage_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carextras',
            name='price',
        ),
        migrations.AddField(
            model_name='carextras',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='extras', to='main_app.car'),
        ),
        migrations.AddField(
            model_name='carextras',
            name='maximum_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='carextras',
            name='minimal_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='carextras',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicleregistrationcertificate',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
