# Generated by Django 4.2.6 on 2023-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_locationtype_alter_carfeatures_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_manufacture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='air_conditioning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='interior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='number_of_doors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='required_license_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='roof',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='seats',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='franchise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='priceandconditions',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priceandconditions',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='priceandconditions',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
