# Generated by Django 4.2.6 on 2023-11-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_car_year_of_manufacture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargallery',
            name='description',
        ),
    ]
