# Generated by Django 4.2.6 on 2023-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_cargallery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfeatures',
            name='airbags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='powered_windows',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='side_wheel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
