# Generated by Django 4.2.6 on 2023-11-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_vehicleregistrationcertificate_chassis_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('raise_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cars', models.ManyToManyField(blank=True, related_name='raise_cars', to='main_app.car')),
            ],
        ),
    ]
