# Generated by Django 4.2.6 on 2023-12-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_country_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
        ),
    ]
