# Generated by Django 4.2.6 on 2023-12-20 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_city_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_month', models.IntegerField()),
                ('start_day', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('end_day', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='end_day',
            new_name='max_days',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='start_day',
            new_name='min_days',
        ),
        migrations.DeleteModel(
            name='PriceAndConditions',
        ),
        migrations.AddField(
            model_name='rate',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.season'),
        ),
        migrations.AddField(
            model_name='rate',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.tariff'),
        ),
    ]
