# Generated by Django 4.2.6 on 2023-12-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_rate_season_rename_end_day_tariff_max_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=15)),
                ('is_primary_whatsapp', models.BooleanField(default=False)),
                ('is_primary_viber', models.BooleanField(default=False)),
                ('is_primary_telegram', models.BooleanField(default=False)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_secondary_whatsapp', models.BooleanField(default=False)),
                ('is_secondary_viber', models.BooleanField(default=False)),
                ('is_secondary_telegram', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='place',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='location_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.locationtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.customer'),
        ),
    ]
