# Generated by Django 4.2.6 on 2023-12-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('service_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='main_app.booking')),
                ('car_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.carextras')),
            ],
        ),
    ]
