# Generated by Django 4.2.6 on 2024-01-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_company_central_office_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='central_office_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
        ),
    ]
