# Generated by Django 4.2.6 on 2024-01-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_alter_company_central_office_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='location',
        ),
    ]
