# Generated by Django 4.2.6 on 2024-01-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_remove_city_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.company'),
        ),
    ]
