# Generated by Django 4.2.6 on 2024-01-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_tariff_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
    ]
