# Generated by Django 4.2.6 on 2024-04-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_delivery_dealer_locationtype_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='preparation_time',
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='closing_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='opening_time',
            field=models.IntegerField(),
        ),
    ]
