# Generated by Django 4.2.6 on 2024-04-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_remove_workinghours_preparation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='closing_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='opening_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
