# Generated by Django 4.2.6 on 2024-04-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_alter_workinghours_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='closing_time',
        ),
    ]
