# Generated by Django 4.2.6 on 2024-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_remove_workinghours_closing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='closing_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
