# Generated by Django 4.2.6 on 2024-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_workinghours_closing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
