# Generated by Django 4.2.6 on 2024-04-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_publicholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.company'),
        ),
        migrations.AddField(
            model_name='raise',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.company'),
        ),
    ]
